//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalurgical_Plant.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int id { get; set; }
        public Nullable<int> kr70 { get; set; }
        public Nullable<int> kr80 { get; set; }
        public Nullable<int> kr100 { get; set; }
    }
}
